# Generated by Django 5.1.3 on 2024-12-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datasource", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
