# Generated by Django 5.2.1 on 2025-06-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0002_datasource_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='type',
            field=models.CharField(choices=[('POSTGRES', 'Postgres'), ('MYSQL', 'MySQL'), ('MONGO', 'MongoDB'), ('REDIS', 'Redis')], default='POSTGRES', max_length=10),
        ),
    ]
