# Generated by Django 5.2.2 on 2026-01-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0003_alter_datasource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='type',
            field=models.CharField(choices=[('POSTGRES', 'Postgres'), ('MYSQL', 'MySQL')], default='POSTGRES', max_length=10),
        ),
    ]
