from django.urls import path
from .views import (
    DataSourceView,
    DataSourceTestConnectionView,
    DataSourceTablesMetadataView,
    DataSourceSchemasMetadataView,
    DataSourceDetailMetadataView,
    DataSourceConnectionTypesView,
    DataSourceConnectionTypesFormFieldsView,
)

urlpatterns = [
    path("datasource/", DataSourceView.as_view(), name="datasource-list"),
    path(
        "datasource/detail/<uuid:id>/",
        DataSourceView.as_view(),
        name="datasource-detail",
    ),
    path(
        "datasource/query/<uuid:id>/",
        DataSourceView.as_view(),
        name="datasource-query",
    ),
    path(
        "datasource/test/",
        DataSourceTestConnectionView.as_view(),
        name="datasource-test",
    ),
    path(
        "datasource/test/<uuid:id>/",
        DataSourceTestConnectionView.as_view(),
        name="datasource-test",
    ),
    path(
        "datasource-metadata/tables/<uuid:id>/",
        DataSourceDetailMetadataView.as_view(),
        name="datasource-metadata",
    ),
    path(
        "datasource-metadata/tables/<uuid:id>/<str:table_name>/",
        DataSourceDetailMetadataView.as_view(),
        name="datasource-metadata",
    ),
    path(
        "datasource-metadata/tables/<uuid:id>/",
        DataSourceDetailMetadataView.as_view(),
        name="datasource-metadata-update",
    ),
    path(
        "datasource-metadata/schemas/<uuid:id>/",
        DataSourceSchemasMetadataView.as_view(),
        name="datasource-metadata-update",
    ),
    path(
        "datasource-metadata/schemas/<uuid:id>/<str:schema>/",
        DataSourceTablesMetadataView.as_view(),
        name="datasource-metadata-update",
    ),
    path(
        "datasource/connection-types/",
        DataSourceConnectionTypesView.as_view(),
        name="datasource-connection-types",
    ),
    path(
        "datasource/connection-type-form/<str:id>",
        DataSourceConnectionTypesFormFieldsView.as_view(),
        name="datasource-connection-types",
    ),
]
