# Generated by Django 5.1.3 on 2024-11-19 05:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NeuralNetworkModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('num_layers', models.IntegerField()),
                ('layer_configurations', models.JSONField(help_text="JSON structure: [{'type': 'dense', 'units': 64, 'activation': 'relu'}, ...]")),
                ('input_shape', models.CharField(help_text="e.g., '(64,)'", max_length=255)),
                ('output_shape', models.CharField(help_text="e.g., '(10,)'", max_length=255)),
                ('learning_rate', models.FloatField()),
                ('batch_size', models.IntegerField()),
                ('epochs', models.IntegerField()),
                ('optimizer', models.CharField(choices=[('sgd', 'SGD'), ('adam', 'Adam')], max_length=50)),
                ('optimizer_params', models.JSONField(blank=True, null=True)),
                ('trained_model_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Neural Network',
                'verbose_name_plural': 'Neural Networks',
            },
        ),
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('data_file', models.FileField(upload_to='training_data/')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Training Data',
                'verbose_name_plural': 'Training Data',
            },
        ),
    ]
