# Generated by Django 5.2.2 on 2026-01-20 22:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuadraticTrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.JSONField(help_text='Precomputed input features for training')),
                ('output_data', models.JSONField(help_text='Expected output values for training')),
            ],
            options={
                'db_table': 'test_quadratictrainingdata',
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='Unnamed Dataset', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('minio_csv_key', models.CharField(blank=True, help_text='MinIO key for CSV file', max_length=512, null=True)),
                ('minio_zip_key', models.CharField(blank=True, help_text='MinIO key for ZIP archive', max_length=512, null=True)),
                ('minio_images_prefix', models.CharField(blank=True, help_text='MinIO prefix for extracted images', max_length=512, null=True)),
                ('dataset_type', models.CharField(choices=[('tabular', 'Tabular Data'), ('image', 'Image Dataset'), ('text', 'Text Dataset'), ('time_series', 'Time Series'), ('mixed', 'Mixed Dataset')], default='tabular', max_length=20)),
                ('dataset_purpose', models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression'), ('clustering', 'Clustering'), ('segmentation', 'Segmentation'), ('anomaly_detection', 'Anomaly Detection'), ('recommendation', 'Recommendation'), ('general', 'General Purpose')], default='general', max_length=20)),
                ('data_quality', models.CharField(choices=[('excellent', 'Excellent (>95% complete)'), ('good', 'Good (85-95% complete)'), ('fair', 'Fair (70-85% complete)'), ('poor', 'Poor (<70% complete)'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('column_count', models.IntegerField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('encoding', models.CharField(default='utf-8', max_length=50)),
                ('column_info', models.JSONField(blank=True, default=dict)),
                ('statistics', models.JSONField(blank=True, default=dict)),
                ('quality_report', models.JSONField(blank=True, default=dict)),
                ('preview_data', models.JSONField(blank=True, default=list)),
                ('segment_labels', models.JSONField(blank=True, default=dict)),
                ('model_recommendations', models.JSONField(blank=True, default=dict)),
                ('join_metadata', models.JSONField(blank=True, default=dict)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_errors', models.TextField(blank=True, null=True)),
                ('last_analyzed', models.DateTimeField(blank=True, null=True)),
                ('is_image_dataset', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('source_datasets', models.ManyToManyField(blank=True, related_name='derived_datasets', to='app.dataset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(help_text="Segment name (e.g., 'High Value Customers')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of this segment', null=True)),
                ('color', models.CharField(default='#3b82f6', help_text='Hex color for UI visualization', max_length=7)),
                ('row_count', models.IntegerField(default=0, help_text='Number of rows in this segment')),
                ('rules', models.JSONField(blank=True, default=dict, help_text='Optional automated rules for segment assignment (filters, conditions)')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='app.dataset')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('dataset', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='Unnamed Model', max_length=255)),
                ('target_column', models.CharField(default='target', max_length=255)),
                ('training_config', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('training', 'Training'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('model_file', models.FileField(blank=True, help_text='Path to the trained model file', null=True, upload_to='trained_models/')),
                ('training_log', models.TextField(blank=True, default='Training not started.', null=True)),
                ('model_type', models.CharField(choices=[('logistic_regression', 'Logistic Regression'), ('decision_tree', 'Decision Tree'), ('random_forest', 'Random Forest'), ('svm', 'Support Vector Machine'), ('naive_bayes', 'Naive Bayes'), ('knn', 'k-Nearest Neighbours'), ('gradient_boosting', 'Gradient Boosting (sklearn)'), ('xgboost', 'XGBoost'), ('lightgbm', 'LightGBM'), ('adaboost', 'AdaBoost'), ('neural_network', 'Neural Network (PyTorch)'), ('cnn', 'Convolutional Neural Network (CNN)'), ('resnet', 'ResNet (Transfer Learning)'), ('vgg', 'VGG (Transfer Learning)'), ('efficientnet', 'EfficientNet (Transfer Learning)'), ('rnn', 'Recurrent Neural Network (RNN)'), ('lstm', 'Long Short-Term Memory (LSTM)'), ('gru', 'Gated Recurrent Unit (GRU)'), ('kmeans', 'K-Means Clustering'), ('dbscan', 'DBSCAN Clustering'), ('hierarchical', 'Hierarchical Clustering'), ('gaussian_mixture', 'Gaussian Mixture Model'), ('mean_shift', 'Mean Shift Clustering')], default='logistic_regression', max_length=50)),
                ('test_size', models.FloatField(default=0.2)),
                ('random_state', models.IntegerField(default=42)),
                ('max_iter', models.IntegerField(default=1000)),
                ('accuracy', models.FloatField(blank=True, help_text='Model accuracy score', null=True)),
                ('prediction_schema', models.JSONField(blank=True, default=dict, help_text='Schema describing required input fields for prediction')),
                ('analytics_data', models.JSONField(blank=True, default=dict, help_text='Detailed analytics data including metrics, confusion matrix, feature importance, etc.')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dataset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.JSONField(blank=True, default=list)),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_run', to='app.mlmodel')),
            ],
        ),
        migrations.CreateModel(
            name='RowSegmentLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('row_index', models.IntegerField(help_text='Index of the row in the dataset')),
                ('row_data', models.JSONField(default=dict, help_text='Snapshot of row data for quick reference')),
                ('assignment_method', models.CharField(choices=[('manual', 'Manual'), ('rule', 'Rule-based'), ('ml', 'ML-based')], default='manual', max_length=20)),
                ('confidence', models.FloatField(default=1.0, help_text='Confidence score (1.0 for manual, varies for automated)')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this assignment', null=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='User who assigned this label', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_labels', to='app.datasegment')),
            ],
            options={
                'ordering': ['row_index'],
                'indexes': [models.Index(fields=['row_index'], name='app_rowsegm_row_ind_7a0f9c_idx'), models.Index(fields=['segment', 'row_index'], name='app_rowsegm_segment_d6ec45_idx')],
                'unique_together': {('segment', 'row_index')},
            },
        ),
    ]
