# Generated by Django 5.2.2 on 2025-06-07 00:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mlalgorithm",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="mlalgorithm",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="mlmodel",
            name="algorithm",
        ),
        migrations.RemoveField(
            model_name="neuralnetworkalgorithm",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="neuralnetworkalgorithm",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="randomforestalgorithm",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="randomforestalgorithm",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="xgboostalgorithm",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="xgboostalgorithm",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="mlmodel",
            name="description",
        ),
        migrations.RemoveField(
            model_name="mlmodel",
            name="feature_columns",
        ),
        migrations.RemoveField(
            model_name="mlmodel",
            name="metrics",
        ),
        migrations.RemoveField(
            model_name="mlmodel",
            name="random_state",
        ),
        migrations.RemoveField(
            model_name="mlmodel",
            name="status",
        ),
        migrations.RemoveField(
            model_name="mlmodel",
            name="target_column",
        ),
        migrations.RemoveField(
            model_name="mlmodel",
            name="task_type",
        ),
        migrations.RemoveField(
            model_name="mlmodel",
            name="test_size",
        ),
        migrations.RemoveField(
            model_name="mlmodel",
            name="training_data",
        ),
        migrations.AddField(
            model_name="mlmodel",
            name="training_log",
            field=models.TextField(
                blank=True, default="Training not started.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mlmodel",
            name="model_file",
            field=models.FileField(
                blank=True,
                help_text="Path to the trained model file",
                null=True,
                upload_to="trained_models/",
            ),
        ),
        migrations.AlterField(
            model_name="mlmodel",
            name="name",
            field=models.CharField(default="Unnamed Model", max_length=255),
        ),
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(default="Untitled Dataset", max_length=255)),
                (
                    "file",
                    models.FileField(
                        help_text="Upload a CSV file",
                        upload_to="datasets/",
                        validators=[
                            django.core.validators.FileExtensionValidator(["csv"])
                        ],
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="mlmodel",
            name="dataset",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.dataset",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="LinearRegressionAlgorithm",
        ),
        migrations.DeleteModel(
            name="MLAlgorithm",
        ),
        migrations.DeleteModel(
            name="NeuralNetworkAlgorithm",
        ),
        migrations.DeleteModel(
            name="RandomForestAlgorithm",
        ),
        migrations.DeleteModel(
            name="XGBoostAlgorithm",
        ),
    ]
