# Generated by Django 5.1.3 on 2024-12-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuralnetworkmodel',
            name='input_shape',
            field=models.CharField(help_text="e.g., '(9,)'", max_length=255),
        ),
        migrations.AlterField(
            model_name='neuralnetworkmodel',
            name='layer_configurations',
            field=models.JSONField(help_text="JSON structure: [{'type': 'dense', 'in_features': 9, 'out_features': 128, 'activation': 'relu'}, ...]"),
        ),
        migrations.AlterField(
            model_name='neuralnetworkmodel',
            name='output_shape',
            field=models.CharField(help_text="e.g., '(2,)'", max_length=255),
        ),
    ]
