# Generated by Django 5.2.2 on 2025-06-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_remove_mlalgorithm_content_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mlmodel",
            name="target_column",
            field=models.CharField(default="target", max_length=255),
        ),
    ]
