# Generated by Django 5.1.3 on 2024-12-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_neuralnetworkmodel_input_shape_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuadraticTrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.JSONField(help_text='Precomputed input features for training')),
                ('output_data', models.JSONField(help_text='Expected output values for training')),
            ],
            options={
                'db_table': 'test_quadratictrainingdata',
            },
        ),
    ]
