# Generated by Django 5.2.2 on 2026-01-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_mlmodel_model_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='model_type',
            field=models.CharField(choices=[('logistic_regression', 'Logistic Regression'), ('decision_tree', 'Decision Tree'), ('random_forest', 'Random Forest'), ('svm', 'Support Vector Machine'), ('naive_bayes', 'Naive Bayes'), ('knn', 'k-Nearest Neighbours'), ('gradient_boosting', 'Gradient Boosting (sklearn)'), ('xgboost', 'XGBoost'), ('lightgbm', 'LightGBM'), ('adaboost', 'AdaBoost'), ('neural_network', 'Neural Network (PyTorch)'), ('cnn', 'Convolutional Neural Network (CNN)'), ('resnet', 'ResNet'), ('vgg', 'VGG'), ('efficientnet', 'EfficientNet'), ('lstm', 'LSTM'), ('kmeans', 'K-Means Clustering'), ('dbscan', 'DBSCAN Clustering'), ('hierarchical', 'Hierarchical Clustering'), ('gaussian_mixture', 'Gaussian Mixture Model'), ('mean_shift', 'Mean Shift Clustering')], default='logistic_regression', max_length=50),
        ),
    ]
