# Generated by Django 5.2.2 on 2026-01-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_mlmodel_model_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='model_type',
            field=models.CharField(choices=[('logistic_regression', 'Logistic Regression'), ('decision_tree', 'Decision Tree Classifier'), ('random_forest', 'Random Forest Classifier'), ('svm', 'Support Vector Classifier (SVC)'), ('naive_bayes', 'Naive Bayes'), ('knn', 'K-Nearest Neighbors Classifier'), ('gradient_boosting', 'Gradient Boosting Classifier'), ('xgboost', 'XGBoost Classifier'), ('lightgbm', 'LightGBM Classifier'), ('adaboost', 'AdaBoost Classifier'), ('linear_regression', 'Linear Regression'), ('decision_tree_regressor', 'Decision Tree Regressor'), ('random_forest_regressor', 'Random Forest Regressor'), ('svr', 'Support Vector Regressor (SVR)'), ('knn_regressor', 'K-Nearest Neighbors Regressor'), ('gradient_boosting_regressor', 'Gradient Boosting Regressor'), ('xgboost_regressor', 'XGBoost Regressor'), ('lightgbm_regressor', 'LightGBM Regressor'), ('adaboost_regressor', 'AdaBoost Regressor'), ('neural_network', 'Neural Network (PyTorch)'), ('cnn', 'Convolutional Neural Network (CNN)'), ('kmeans', 'K-Means Clustering'), ('dbscan', 'DBSCAN Clustering'), ('hierarchical', 'Hierarchical Clustering'), ('gaussian_mixture', 'Gaussian Mixture Model'), ('mean_shift', 'Mean Shift Clustering')], default='logistic_regression', max_length=50),
        ),
    ]
