# Generated by Django 5.2.2 on 2025-06-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_dataset_csv_file_dataset_is_image_dataset_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mlmodel",
            name="model_file",
        ),
        migrations.AlterField(
            model_name="mlmodel",
            name="model_type",
            field=models.CharField(
                choices=[
                    ("logistic_regression", "Logistic Regression"),
                    ("random_forest", "Random Forest"),
                    ("svm", "Support Vector Machine"),
                    ("naive_bayes", "Naive Bayes"),
                    ("knn", "k-Nearest Neighbours"),
                    ("GRADIENT_BOOSTING", "Gradient Boosting"),
                    ("neural_network", "Neural Network (PyTorch)"),
                    ("cnn", "Convolutional Neural Network (CNN)"),
                ],
                default="logistic_regression",
                max_length=50,
            ),
        ),
    ]
