# Generated by Django 5.2.2 on 2025-06-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_mlmodel_model_file_alter_mlmodel_model_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='model_file',
            field=models.FileField(blank=True, help_text='Path to the trained model file', null=True, upload_to='trained_models/'),
        ),
    ]
