# Generated by Django 5.2.1 on 2025-09-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_mlmodel_model_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='accuracy',
            field=models.FloatField(blank=True, help_text='Model accuracy score', null=True),
        ),
    ]
