# Generated by Django 5.2.1 on 2025-10-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_add_prediction_schema_to_mlmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='model_type',
            field=models.CharField(choices=[('logistic_regression', 'Logistic Regression'), ('decision_tree', 'Decision Tree'), ('random_forest', 'Random Forest'), ('svm', 'Support Vector Machine'), ('naive_bayes', 'Naive Bayes'), ('knn', 'k-Nearest Neighbours'), ('gradient_boosting', 'Gradient Boosting (sklearn)'), ('xgboost', 'XGBoost'), ('lightgbm', 'LightGBM'), ('adaboost', 'AdaBoost'), ('neural_network', 'Neural Network (PyTorch)'), ('cnn', 'Convolutional Neural Network (CNN)'), ('resnet', 'ResNet (Transfer Learning)'), ('vgg', 'VGG (Transfer Learning)'), ('efficientnet', 'EfficientNet (Transfer Learning)'), ('rnn', 'Recurrent Neural Network (RNN)'), ('lstm', 'Long Short-Term Memory (LSTM)'), ('gru', 'Gated Recurrent Unit (GRU)')], default='logistic_regression', max_length=50),
        ),
    ]
